services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://bizzline:foobar@postgres:5432/news
      - CHECK_INTERVAL_HOURS=1 # Check every hour
    networks:
      - bizzline-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:latest
    networks:
      - bizzline-network
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=bizzline
      - POSTGRES_PASSWORD=foobar
      - POSTGRES_DB=news
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bizzline"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  bizzline-network:
    driver: bridge
