"""Initial migration

Revision ID: 9a3c632ec0db
Revises: 
Create Date: 2024-11-20 17:01:45.610182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a3c632ec0db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_article_versions_article_id', table_name='article_versions')
    op.drop_index('ix_article_versions_id', table_name='article_versions')
    op.drop_table('article_versions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diff', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_versions_article_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='article_versions_pkey')
    )
    op.create_index('ix_article_versions_id', 'article_versions', ['id'], unique=False)
    op.create_index('ix_article_versions_article_id', 'article_versions', ['article_id'], unique=False)
    # ### end Alembic commands ###
